/*

Script para trazer a quantidade de clientes separados pela faixa de volume medido m³

*/

WITH FX_VOL AS (
    -- Gera as faixas unitárias de 1 a 100
    SELECT 
        (LEVEL - 1) AS FAIXA_INICIO,
        LEVEL AS FAIXA_FIM,
        'DE ' || (LEVEL - 1) || ' ATÉ ' || LEVEL || ' M3' AS FAIXA_VOLUME,
        LEVEL AS ORDEM
    FROM DUAL
    CONNECT BY LEVEL <= 100
    UNION ALL
    -- Adiciona faixa para valores maiores que 100
    SELECT 
        100 AS FAIXA_INICIO,
        NULL AS FAIXA_FIM,
        'ACIMA DE 100 M3' AS FAIXA_VOLUME,
        101 AS ORDEM
    FROM DUAL
),
LEI AS (
    SELECT 
        AAMM_REFERENCIA,
        DH_LEITURA_ATUAL,
        FAIXA_VOLUME FAIXA_VOLUME_MEDIDO,
        ID_PDE,
        VARIACAO_VOLUME_MEDIDO,
        CONSUMO_MEDIO,
        CASE 
            WHEN VARIACAO_VOLUME_MEDIDO = 0 AND CONSUMO_MEDIO = 0 THEN 0
            WHEN VARIACAO_VOLUME_MEDIDO = 0 AND CONSUMO_MEDIO > 0 THEN CONSUMO_MEDIO * 100
            WHEN VARIACAO_VOLUME_MEDIDO > 0 AND CONSUMO_MEDIO = 0 THEN VARIACAO_VOLUME_MEDIDO * 100
            ELSE ROUND(((VARIACAO_VOLUME_MEDIDO - CONSUMO_MEDIO) / CONSUMO_MEDIO) * 100, 4)
        END VARIACAO_MEDIA
    FROM (
        SELECT 
            TO_CHAR(EXTRACT(YEAR FROM DH_LEITURA_ATUAL)) ||
            CASE 
                WHEN EXTRACT(MONTH FROM DH_LEITURA_ATUAL) < 10 THEN '0' || TO_CHAR(EXTRACT(MONTH FROM DH_LEITURA_ATUAL))
                ELSE TO_CHAR(EXTRACT(MONTH FROM DH_LEITURA_ATUAL))
            END AS AAMM_REFERENCIA,
            DH_LEITURA_ATUAL,
            FAIXA_VOLUME,
            ID_PDE,
            (NR_LEITURA_ATUAL - NR_LEITURA_ANTERIOR) VARIACAO_VOLUME_MEDIDO,
            CONSUMO_MEDIO,
            ROW_NUMBER() OVER(PARTITION BY ID_PDE ORDER BY DH_LEITURA_ATUAL DESC, DT_INCLUSAO DESC, DT_INSERCAO DESC) CN
        FROM ORA_DW.MOV_LEITURA L
        JOIN FX_VOL F
            ON (NR_LEITURA_ATUAL - NR_LEITURA_ANTERIOR) >= F.FAIXA_INICIO
           AND ((NR_LEITURA_ATUAL - NR_LEITURA_ANTERIOR) <= F.FAIXA_FIM OR F.FAIXA_FIM IS NULL)
        WHERE 
            ST_LEITURA = 'FAT'
            -- 🔍 Filtro para outubro/2025
            AND TRUNC(DH_LEITURA_ATUAL) BETWEEN TO_DATE('01/10/2025','DD/MM/YYYY') 
                                             AND TO_DATE('31/10/2025','DD/MM/YYYY')
            AND (NR_LEITURA_ATUAL - NR_LEITURA_ANTERIOR) > 0
    )
    WHERE CN = 1
),
RSM AS (
    SELECT 
        L.AAMM_REFERENCIA,
        T.DS_CD_CATEGORIA_USO,
        L.FAIXA_VOLUME_MEDIDO,
        L.ID_PDE,
        L.VARIACAO_MEDIA,
        CASE WHEN VARIACAO_MEDIA < -30 THEN 1 ELSE 0 END VARIACAO_MEDIA_MENOR_QUE_MENOS_30_POR_CENTO,
        CASE WHEN VARIACAO_MEDIA >= -30 AND VARIACAO_MEDIA < -20 THEN 1 ELSE 0 END VARIACAO_MEDIA_ENTRE_MENOS_30_E_MENOS_20_POR_CENTO,
        CASE WHEN VARIACAO_MEDIA >= -20 AND VARIACAO_MEDIA < -10 THEN 1 ELSE 0 END VARIACAO_MEDIA_ENTRE_MENOS_20_E_MENOS_10_POR_CENTO,
        CASE WHEN VARIACAO_MEDIA >= -10 AND VARIACAO_MEDIA < 0 THEN 1 ELSE 0 END VARIACAO_MEDIA_ENTRE_MENOS_10_E_0_POR_CENTO,
        CASE WHEN VARIACAO_MEDIA = 0 THEN 1 ELSE 0 END VARIACAO_MEDIA_IGUAL_A_0_POR_CENTO,
        CASE WHEN VARIACAO_MEDIA > 0 AND VARIACAO_MEDIA < 10 THEN 1 ELSE 0 END VARIACAO_MEDIA_ENTRE_0_E_MAIS_10_POR_CENTO,
        CASE WHEN VARIACAO_MEDIA >= 10 AND VARIACAO_MEDIA < 20 THEN 1 ELSE 0 END VARIACAO_MEDIA_ENTRE_MAIS_10_E_MAIS_20_POR_CENTO,
        CASE WHEN VARIACAO_MEDIA >= 20 AND VARIACAO_MEDIA < 30 THEN 1 ELSE 0 END VARIACAO_MEDIA_ENTRE_MAIS_20_E_MAIS_30_POR_CENTO,
        CASE WHEN VARIACAO_MEDIA >= 30 AND VARIACAO_MEDIA < 40 THEN 1 ELSE 0 END VARIACAO_MEDIA_ENTRE_MAIS_30_E_MAIS_40_POR_CENTO,
        CASE WHEN VARIACAO_MEDIA >= 40 AND VARIACAO_MEDIA < 50 THEN 1 ELSE 0 END VARIACAO_MEDIA_ENTRE_MAIS_40_E_MAIS_50_POR_CENTO,
        CASE WHEN VARIACAO_MEDIA >= 50 AND VARIACAO_MEDIA < 100 THEN 1 ELSE 0 END VARIACAO_MEDIA_ENTRE_MAIS_50_E_MAIS_100_POR_CENTO,
        CASE WHEN VARIACAO_MEDIA >= 100 AND VARIACAO_MEDIA < 300 THEN 1 ELSE 0 END VARIACAO_MEDIA_ENTRE_MAIS_100_E_MAIS_300_POR_CENTO,
        CASE WHEN VARIACAO_MEDIA >= 300 THEN 1 ELSE 0 END VARIACAO_MEDIA_MAIOR_QUE_MAIS_300_POR_CENTO
    FROM LEI L
    LEFT JOIN ORA_DW.CAD_PDE P
        ON L.ID_PDE = P.ID_PDE
       AND TRUNC(L.DH_LEITURA_ATUAL) BETWEEN TRUNC(P.DT_INI) AND TRUNC(P.DT_FIM)
    LEFT JOIN ORA_DW.CAD_FORNECIMENTO F
        ON P.ID_FORNECIMENTO = F.ID_FORNECIMENTO
       AND TRUNC(L.DH_LEITURA_ATUAL) BETWEEN TRUNC(F.DT_INI) AND TRUNC(F.DT_FIM)
    LEFT JOIN ORA_DW.TBA_CD_CATEGORIA_USO T
        ON F.CD_CATEGORIA_USO = T.CD_CATEGORIA_USO
)
SELECT 
    AAMM_REFERENCIA,
    DS_CD_CATEGORIA_USO,
    FAIXA_VOLUME_MEDIDO,
    COUNT(DISTINCT ID_PDE) QTD_CLIENTES,
    ROUND(AVG(VARIACAO_MEDIA), 4) VARIACAO_MEDIA,
    SUM(VARIACAO_MEDIA_MENOR_QUE_MENOS_30_POR_CENTO) QTD_VAR_MENOS_30,
    SUM(VARIACAO_MEDIA_ENTRE_MENOS_30_E_MENOS_20_POR_CENTO) QTD_VAR_MENOS_30_20,
    SUM(VARIACAO_MEDIA_ENTRE_MENOS_20_E_MENOS_10_POR_CENTO) QTD_VAR_MENOS_20_10,
    SUM(VARIACAO_MEDIA_ENTRE_MENOS_10_E_0_POR_CENTO) QTD_VAR_MENOS_10_0,
    SUM(VARIACAO_MEDIA_IGUAL_A_0_POR_CENTO) QTD_VAR_IGUAL_0,
    SUM(VARIACAO_MEDIA_ENTRE_0_E_MAIS_10_POR_CENTO) QTD_VAR_0_10,
    SUM(VARIACAO_MEDIA_ENTRE_MAIS_10_E_MAIS_20_POR_CENTO) QTD_VAR_10_20,
    SUM(VARIACAO_MEDIA_ENTRE_MAIS_20_E_MAIS_30_POR_CENTO) QTD_VAR_20_30,
    SUM(VARIACAO_MEDIA_ENTRE_MAIS_30_E_MAIS_40_POR_CENTO) QTD_VAR_30_40,
    SUM(VARIACAO_MEDIA_ENTRE_MAIS_40_E_MAIS_50_POR_CENTO) QTD_VAR_40_50,
    SUM(VARIACAO_MEDIA_ENTRE_MAIS_50_E_MAIS_100_POR_CENTO) QTD_VAR_50_100,
    SUM(VARIACAO_MEDIA_ENTRE_MAIS_100_E_MAIS_300_POR_CENTO) QTD_VAR_100_300,
    SUM(VARIACAO_MEDIA_MAIOR_QUE_MAIS_300_POR_CENTO) QTD_VAR_MAIOR_300
FROM RSM
GROUP BY 
    AAMM_REFERENCIA,
    DS_CD_CATEGORIA_USO,
    FAIXA_VOLUME_MEDIDO
ORDER BY 
    AAMM_REFERENCIA,
    DS_CD_CATEGORIA_USO,
    FAIXA_VOLUME_MEDIDO