/*

Script para trazer o volume medido e faturado por range de DATA
Esse script é uma variação do script que tem no Sandbox

*/

WITH parametros_periodo AS (
    SELECT
        DATE '2024-03-01' AS dt_inicio,
        DATE '2024-04-01' AS dt_fim
    FROM dual
),

faturas_filtradas AS (
    SELECT
        FATURA.*
    FROM
        ORA_DW.MOV_FATURA FATURA
        CROSS JOIN parametros_periodo p
    WHERE
        FATURA.CD_SECCIONAL IN ('SOR', 'SOF')
        AND FATURA.ID_FATURA NOT IN (
            SELECT ID_FATURA_DESTINO
            FROM ORA_DW.MOV_REFATURAMENTO
        )
        AND FATURA.DT_EMISSAO_FATURA >= p.dt_inicio
        AND FATURA.DT_EMISSAO_FATURA <  p.dt_fim
),

leituras_medidas AS (
    SELECT
        LEIT.ID_FATURA,
        SUM(LEIT.QTD_CONSUMO_MEDIDO_AGUA)   AS QTD_CONSUMO_MEDIDO_AGUA,
        SUM(LEIT.QTD_CONSUMO_MEDIDO_ESGOTO) AS QTD_CONSUMO_MEDIDO_ESGOTO,
        SUM(LEIT.QTD_CONSUMO_MEDIDO_END)    AS QTD_CONSUMO_MEDIDO_END
    FROM
        ora_dw.mov_leitura LEIT
        JOIN ORA_DW.MOV_FATURA FAT ON LEIT.ID_FATURA = FAT.ID_FATURA
        LEFT JOIN ORA_DW.CAD_FORNECIMENTO FO ON FO.ID_FORNECIMENTO = FAT.ID_FORNECIMENTO
            AND (FAT.DT_EMISSAO_FATURA BETWEEN FO.DT_INI AND FO.DT_FIM OR FO.DT_FIM IS NULL)
        CROSS JOIN parametros_periodo p
    WHERE
        FAT.ID_FATURA NOT IN (
            SELECT ID_FATURA_DESTINO
            FROM ORA_DW.MOV_REFATURAMENTO
        )
        AND NVL(FO.TP_FORNECIMENTO, '-1') NOT IN ('13','14','15','39','40','41','42')
        AND NVL(LEIT.TP_LEITURA_LOGICO, '-1') NOT IN ('MA','SZ')
        AND FAT.CD_SECCIONAL IN ('SOR','SOF')
        AND FAT.DT_EMISSAO_FATURA >= p.dt_inicio
        AND FAT.DT_EMISSAO_FATURA <  p.dt_fim
    GROUP BY
        LEIT.ID_FATURA
),

leituras_medias AS (
    SELECT
        LEIT.ID_FATURA,
        AVG(LEIT.CONSUMO_MEDIO) AS QTD_CONSUMO_MEDIO,
        SUM(LEIT.QTD_DIAS)      AS QTD_DIAS
    FROM
        ora_dw.mov_leitura LEIT
        JOIN ORA_DW.MOV_FATURA FAT ON LEIT.ID_FATURA = FAT.ID_FATURA
        CROSS JOIN parametros_periodo p
    WHERE
        FAT.ID_FATURA NOT IN (
            SELECT ID_FATURA_DESTINO
            FROM ORA_DW.MOV_REFATURAMENTO
        )
        AND FAT.CD_SECCIONAL IN ('SOR','SOF')
        AND FAT.DT_EMISSAO_FATURA >= p.dt_inicio
        AND FAT.DT_EMISSAO_FATURA <  p.dt_fim
    GROUP BY
        LEIT.ID_FATURA
)

SELECT
    FATURA.ID_FATURA,
    FATURA.DT_EMISSAO_FATURA,
    NVL(PDE.ID_PDE, '-1')                            AS ID_PDE,
    NVL(FORN.ID_FORNECIMENTO, '-1')                  AS ID_FORNECIMENTO,
    NVL(SUJ.ID_SUJEITO, '-1')                        AS ID_SUJEITO,
    NVL(FATURA.CD_ATC, '-1')                         AS CD_ATC,
    NVL(HC.DS_CD_ATC, '-1')                          AS DS_CD_ATC,
    NVL(HC.CD_UGR_ADMIN, '-1')                       AS CD_UGR_ADMIN,
    NVL(HC.DS_CD_UGR_ADMIN, '-1')                    AS DS_CD_UGR_ADMIN,
    NVL(HC.CD_SUPERINTENDENCIA, '-1')                AS CD_SUPERINTENDENCIA,
    NVL(HC.DS_CD_SUPERINTENDENCIA, '-1')             AS DS_CD_SUPERINTENDENCIA,
    NVL(HC.CD_DIRETORIA, '-1')                       AS CD_DIRETORIA,
    NVL(HC.DS_CD_DIRETORIA, '-1')                    AS DS_CD_DIRETORIA,
    NVL(PDE.CD_SETOR_FISCAL, '-1')                   AS CD_SETOR_FISCAL,
    NVL(PDE.CD_ROTA, '-1')                           AS CD_ROTA,
    NVL(PDE.CD_QUADRA, '-1')                         AS CD_QUADRA,
    NVL(PDE.CD_LOCAL, '-1')                          AS CD_LOCAL,
    NVL(PDE.CD_VILA, '-1')                           AS CD_VILA,
    NVL(PDE.CD_SUBLOCAL, '-1')                       AS CD_SUBLOCAL,
    NVL(PDE.CD_A_SETOR_ABAST_NETA, '-1')             AS CD_A_SETOR_ABAST_NETA,
    NVL(SA.DS_CD_A_SETOR_ABAST_NETA, '-1')           AS DS_CD_A_SETOR_ABAST_NETA,
    NVL(PDE.CD_A_SIST_PRODUTOR_NETA, '-1')           AS CD_A_SIST_PRODUTOR_NETA,
    NVL(SP.DS_CD_A_SIST_PRODUTOR_NETA, '-1')         AS DS_CD_A_SIST_PRODUTOR_NETA,
    NVL(HC.MUNICIPIO, '-1')                          AS MUNICIPIO,
    NVL(HC.UF, '-1')                                 AS UF,
    NVL(
        REPLACE(
            REPLACE(
                REPLACE(PDE.ID_HIDROMETRO, CHR(13), ''),
            CHR(10), ''),
        ';', ''),
        '-1'
    )                                                AS ID_HIDROMETRO,
    NVL(CATEGORIA.DS_CD_CATEGORIA_USO, '-1')         AS DS_CD_CATEGORIA_USO,
    NVL(PDE.TP_LIGACAO, '-1')                        AS TP_LIGACAO,
    NVL(FORN.TP_MERCADO, '-1')                       AS TP_MERCADO,
    NVL(PROD.DS_CD_PRODUTO, '-1')                    AS DS_CD_PRODUTO,
    NVL(FATURA.CD_GR_FATURAMENTO, '-1')              AS CD_GR_FATURAMENTO,
    NVL(FORN.TP_UTILIZACAO, '-1')                    AS TP_UTILIZACAO,
    NVL(TU.DS_TP_UTILIZACAO, '-1')                   AS DS_TP_UTILIZACAO,
    NVL(FORN.TP_FORNECIMENTO, '-1')                  AS TP_FORNECIMENTO,
    NVL(TPF.DS_TP_FORNECIMENTO, '-1')                AS DS_TP_FORNECIMENTO,
    NVL(SUJ.TP_SUJEITO, '-1')                        AS TP_SUJEITO,
    NVL(FATURA.TP_DOCUMENTO_LOGICO, '-1')            AS TP_DOCUMENTO_LOGICO,
    NVL(DOCLOG.DS_TP_DOCUMENTO_LOGICO, '-1')         AS DS_TP_DOCUMENTO_LOGICO,
    leituras_medias.QTD_DIAS,
    leituras_medias.QTD_CONSUMO_MEDIO,
    FATURA.QTD_CONSUMO_FATURADO_AGUA,
    FATURA.QTD_CONSUMO_FATURADO_ESGOTO,
    FATURA.QTD_CONSUMO_FATURADO_END,
    leituras_medidas.QTD_CONSUMO_MEDIDO_AGUA,
    leituras_medidas.QTD_CONSUMO_MEDIDO_ESGOTO,
    leituras_medidas.QTD_CONSUMO_MEDIDO_END
FROM
    faturas_filtradas FATURA
    LEFT JOIN ORA_DW.CAD_FORNECIMENTO FORN ON FORN.ID_FORNECIMENTO = FATURA.ID_FORNECIMENTO
        AND (FATURA.DT_EMISSAO_FATURA BETWEEN FORN.DT_INI AND FORN.DT_FIM OR FORN.DT_FIM IS NULL)
    LEFT JOIN ORA_DW.CAD_PDE PDE ON FATURA.ID_FORNECIMENTO = PDE.ID_FORNECIMENTO
        AND (FATURA.DT_EMISSAO_FATURA BETWEEN PDE.DT_INI AND PDE.DT_FIM OR PDE.DT_FIM IS NULL)
    LEFT JOIN ORA_DW.CAD_SUJEITO SUJ ON FATURA.ID_SUJEITO = SUJ.ID_SUJEITO
        AND (FATURA.DT_EMISSAO_FATURA BETWEEN SUJ.DT_INI AND SUJ.DT_FIM OR SUJ.DT_FIM IS NULL)
    LEFT JOIN leituras_medidas ON leituras_medidas.ID_FATURA = FATURA.ID_FATURA
    LEFT JOIN leituras_medias  ON leituras_medias.ID_FATURA  = FATURA.ID_FATURA
    LEFT JOIN ORA_DW_TAT.HIERARQUIA_COMERCIAL HC ON HC.CD_ATC = FATURA.CD_ATC
    LEFT JOIN ORA_DW.TBA_TP_FORNECIMENTO TPF ON TPF.TP_FORNECIMENTO = FORN.TP_FORNECIMENTO
    LEFT JOIN ORA_DW.TBA_CD_CATEGORIA_USO CATEGORIA ON CATEGORIA.CD_CATEGORIA_USO = FORN.CD_CATEGORIA_USO
    LEFT JOIN ORA_DW.TBA_CD_PRODUTO PROD ON PROD.CD_PRODUTO = FORN.CD_PRODUTO
    LEFT JOIN ORA_DW.TBA_CD_A_SIST_PRODUTOR_NETA SP ON SP.CD_A_SIST_PRODUTOR_NETA = PDE.CD_A_SIST_PRODUTOR_NETA
    LEFT JOIN ORA_DW.TBA_CD_A_SETOR_ABAST_NETA SA ON SA.CD_A_SETOR_ABAST_NETA = PDE.CD_A_SETOR_ABAST_NETA
    LEFT JOIN ORA_DW.TBA_TP_UTILIZACAO TU ON FORN.TP_UTILIZACAO = TU.TP_UTILIZACAO
    LEFT JOIN ORA_DW.TBA_TP_DOCUMENTO_LOGICO DOCLOG ON FATURA.TP_DOCUMENTO_LOGICO = DOCLOG.TP_DOCUMENTO_LOGICO;